#!/usr/bin/env bash
#
# bootstrap-vps.sh — one-shot production bring-up for OperatorOS on a fresh Ubuntu VPS.
#
# It does EVERYTHING the server-side deploy needs:
#   • installs Docker (if missing)
#   • opens the firewall for web + ssh
#   • auto-detects the public IP and uses <ip>.nip.io as the domain (real HTTPS, no
#     domain purchase needed) — override with:  DOMAIN=yourdomain.com bash scripts/bootstrap-vps.sh
#   • generates a fresh .env with strong secrets (only on first run; never clobbers yours)
#   • builds + starts the prod stack, runs migrations, seeds demo data
#
# Usage (on the server, after `git clone`):
#   cd operatoros && bash scripts/bootstrap-vps.sh
#   # optional: OPENROUTER_API_KEY=sk-... DOMAIN=yourdomain.com bash scripts/bootstrap-vps.sh
#
set -euo pipefail

cd "$(dirname "$0")/.."   # repo root, regardless of where it's invoked from

log() { printf '\n\033[36m▸ %s\033[0m\n' "$*"; }

# ── 1. Docker ─────────────────────────────────────────────────────────────────
if ! command -v docker >/dev/null 2>&1; then
  log "Installing Docker…"
  curl -fsSL https://get.docker.com | sh
else
  log "Docker already installed."
fi

# ── 2. Firewall (allow SSH *before* enabling, to avoid lockout) ────────────────
if command -v ufw >/dev/null 2>&1; then
  log "Configuring firewall (22, 80, 443)…"
  ufw allow 22/tcp  >/dev/null 2>&1 || true
  ufw allow 80/tcp  >/dev/null 2>&1 || true
  ufw allow 443/tcp >/dev/null 2>&1 || true
  ufw --force enable >/dev/null 2>&1 || true
fi

# ── 3. Domain (nip.io fallback) ───────────────────────────────────────────────
PUBLIC_IP="$(curl -fsS https://api.ipify.org || curl -fsS https://ifconfig.me || true)"
DOMAIN="${DOMAIN:-${PUBLIC_IP}.nip.io}"
if [ -z "${DOMAIN}" ] || [ "${DOMAIN}" = ".nip.io" ]; then
  echo "ERROR: could not determine a domain or public IP. Set DOMAIN=... and re-run." >&2
  exit 1
fi
export DOMAIN
log "Using DOMAIN=${DOMAIN}"

# ── 4. .env (first run only — never overwrite existing secrets) ────────────────
gen() { openssl rand -hex "$1" 2>/dev/null || python3 -c "import secrets,sys;print(secrets.token_hex(int(sys.argv[1])))" "$1"; }

if [ ! -f .env ]; then
  log "Generating .env with fresh secrets…"
  SECRET_KEY="$(gen 32)"
  REDIS_PASSWORD="$(gen 16)"
  cat > .env <<EOF
# Generated by bootstrap-vps.sh — edit as needed, then re-run \`make deploy\`.
ENVIRONMENT=production
LOG_LEVEL=INFO
DOMAIN=${DOMAIN}
CORS_ORIGINS=https://app.${DOMAIN}

DATABASE_URL=postgresql+asyncpg://operatoros:operatoros@postgres:5432/operatoros

# REDIS_PASSWORD is auto-injected into REDIS_URL / CELERY_* by app/config.py.
REDIS_URL=redis://redis:6379/0
REDIS_PASSWORD=${REDIS_PASSWORD}

SECRET_KEY=${SECRET_KEY}
JWT_ALGORITHM=HS256
ACCESS_TOKEN_EXPIRE_MINUTES=60

# AI is optional for the demo (seeded screens render without it). Add a key to enable live Q&A.
OPENROUTER_API_KEY=${OPENROUTER_API_KEY:-}
FREE_LLM_ENABLED=true
DEFAULT_LLM_MODEL=anthropic/claude-sonnet-4-20250514
EMBEDDING_MODEL=text-embedding-3-small

# n8n admin (change the password)
N8N_WEBHOOK_URL=https://n8n.${DOMAIN}
N8N_BASIC_AUTH_USER=admin
N8N_BASIC_AUTH_PASSWORD=$(gen 8)

# Optional signup alerts — fill in to enable email/Telegram delivery.
SMTP_HOST=
SMTP_PORT=587
SMTP_USER=
SMTP_PASSWORD=
SMTP_FROM=
SMTP_USE_TLS=true
NOTIFY_EMAIL_TO=
TELEGRAM_BOT_TOKEN=
TELEGRAM_CHAT_ID=
EOF
  echo "  .env created (secrets generated)."
else
  log ".env already exists — leaving it untouched."
fi

# ── 5. Build + start + migrate + seed ─────────────────────────────────────────
COMPOSE="docker compose -f docker-compose.yml -f docker-compose.prod.yml"

log "Building and starting the stack (this pulls images + builds — first run is slow)…"
$COMPOSE up -d --build --wait

log "Running database migrations…"
$COMPOSE exec -T fastapi alembic upgrade head

log "Seeding demo data…"
$COMPOSE exec -T fastapi python -m app.seed

log "Done."
cat <<EOF

────────────────────────────────────────────────────────────
  OperatorOS is live (TLS may take ~30s on first request):

    Landing : https://app.${DOMAIN}
    API     : https://api.${DOMAIN}/api/health
    n8n     : https://n8n.${DOMAIN}

  Demo login:  demo@operatoros.in  /  OperatorOS#2026

  Logs:    $COMPOSE logs -f
  Redeploy after a git pull:   bash scripts/bootstrap-vps.sh
────────────────────────────────────────────────────────────
EOF
